# 公共配置文件
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: "/api"
spring:
  application:
    name: springboot-init
  # 默认 local 环境
  profiles:
    active: local
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    url: jdbc:mysql://${spring.datasource.host}:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=false&useSSL=false
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # Redis 配置
  # todo 需替换配置，然后取消注释
  #  redis:
  #    database: 10
  #    host: localhost
  #    port: 6379
  #    password: 123456
  #    lettuce:
  #      pool:
  #        max-active: 200
  #        max-wait: -1
  #        max-idle: 10
  #        min-idle: 0
  #    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
project:
  folder: D:/tmp/web/
log:
  root:
    level: info
# 对象存储
s3:
  minio:
    accessKey: ${s3.minio.accessKey}
    secretKey: ${s3.minio.secretKey}
    endpoint: ${s3.minio.endpoint}
    bucket: ${s3.minio.bucket}
sa-token:
  token-style: tik
  #  token-prefix: Bearer
  active-timeout: -1
  timeout: 900